<?php
// ;$Id$
function StatusBlock_help ($path, $args) {
	 if ($path == 'admin/help#StatusBlock') {
	    return t('Module to present the current status of the hackspace in a block');
	 }
}
function StatusBlock_block_info() {
  $blocks = array();
  
  $blocks['StatusBlock'] = array(
    'info' => t('A display of the current status of the Space'),
    'cache' => DRUPAL_NO_CACHE
    );
    
    return $blocks;
}

function StatusBlock_block_view($block_name = '') {
  if ($block_name == 'StatusBlock') {
    $block = array ();
    
    $block['subject'] = 'Status des Mainframe';
    $block['content'] = '
    <div class="statusblock-Statuscontainer">
	<a href="http://status.kreativitaet-trifft-technik.de">
      <div class="statusblock-Status statusblock-statusinit">
        <p>Pr&uuml;fe</p>
      </div></a>
      <div class="statusblock-openings">
	<strong>Regul&auml;re &Ouml;ffnungszeiten</strong>
        <table>
          <tr><td>Mo-Fr</td><td>18-23 Uhr</td></tr>
          <tr><td>Sa-So</td><td>15-23:42 Uhr</td></tr>
        </table>
      </div>
    </div>';

    return $block; 
  }
}
?>
